### ISSUE TITLE
Do a first tag

### ISSUE THREAD

**Issue by traversaro** [ami-iit/yarp-device-keyboard-joypad#4]
For integration in robotology-superbuild, thanks!

**Comment by S-Dafarra** [comment]
Thanks @traversaro. I am doing some dev in https://github.com/ami-iit/yarp-device-keyboard-joypad/tree/joypad that I think might fit well in a Release. I need to test it, but it is almost done. If at a certain point this is getting more urgent, feel free to ping me

**Comment by traversaro** [comment]
No problem, it is not urgent!

**Comment by S-Dafarra** [comment]
Here the release: https://github.com/ami-iit/yarp-device-keyboard-joypad/releases/tag/v0.0.1
